services:
  - name: qr-scanner-bot
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromSecret: bot_token
      - key: GSB_API_KEY
        fromSecret: gsb_api_key
      - key: PYTHON_VERSION
        value: '3.11.0'

    # --- БЛОК ДЛЯ ZERO-DOWNTIME --- #
    healthCheckPath: /health # <-- ИСПРАВЛЕНО на /health
    # ------------------------------- #

    autoDeploy: yes
